### ISSUE TITLE
I have an issue

### ISSUE THREAD

**Issue by adiprerepa** [kalkulator413/album-gen-py#1] opened 2022-08-07 06:02 UTC
Your code doesn't work.

**Comment by kalkulator413** [comment] 2022-08-07 06:06
Could you elaborate on this?

**Comment by kalkulator413** [comment] 2022-08-07 06:07
Sorry for closing it. Looks like the issue isn't resolved.

**Comment by adiprerepa** [comment] 2022-08-07 06:10
It's not resolved.

**Comment by kalkulator413** [comment] 2022-08-07 06:16
Neither is my immigration status.

**Comment by kalkulator413** [comment] 2022-08-07 06:36
### _**Ok.**_

**Comment by adiprerepa** [comment] 2022-08-07 06:40
![image](https://user-images.githubusercontent.com/43913660/183278610-47c819bc-0a22-4bbc-af75-1ba6a41e0f50.png)

**Closed** 2022-08-08 02:39 UTC
